from .calendar_view import CalendarView
from .client_view import ClientView
from .dashboard import DashboardView
from .delivery_view import DeliveryView
from .gantt_view import GanttView
from .kanban_view import KanbanView
from .order_view import OrderView
from .payment_view import PaymentView
from .quote_view import QuoteView
from .table_view import TableView
